### ISSUE TITLE
memory resource leak

### ISSUE THREAD

**Issue by disillusion028** [michaeljclark/async_tls_test#1]
Why don't call SSL_free & SSL_CTX_free to recycle memory resource?

**Comment by larkmjc** [comment]
Sure. We could do that.

There is a more complete async SSL example here, that calls SSL_free & SSL_CTX:

- https://github.com/michaeljclark/latypus

**Comment by disillusion028** [comment]
Okey, I had written my own async tls tcp connection, which depends on OpenSSL and a reactor network framework .

**Comment by disillusion028** [comment]
But I get a question, what is the reference between SSL_CTX and a tcp socket? Should http server use one SSL_CTX or a tcp connection use one SSL_CTX?  My http server use a tcp connection pool, if I use One SSL_CTX for one http server,there may many socket fd use one SSL_CTX.

**Comment by larkmjc** [comment]
> But I get a question, what is the reference between SSL_CTX and a tcp socket? Should http server use one SSL_CTX or a tcp connection use one SSL_CTX? My http server use a tcp connection pool, if I use One SSL_CTX for one http server,there may many socket fd use one SSL_CTX.

I guess you have already figured this out, but I believe you create an SSL_CTX for each server socket and if you have virtual hosts, you create one SSL_CTX per virtual host, then implement the callbacks to locate its context based on SNI. e.g.

```
{
   ...
    // set servername callback on the server context
    SSL_CTX_set_tlsext_servername_callback(ctx, &my_tls_servername_cb);
   ...
}
```

then for each virtual host STL_CTX, you load their keys and certificates. here is a possible implementation of the callback:

```
int my_tls_servername_cb(SSL *ssl, int *ad, void *arg)
{
    const char *servername = SSL_get_servername(ssl, TLSEXT_NAMETYPE_host_name);

    if (servername) {
        my_http_server_vhost *vhost = my_lookup_vhost(arg, servername);

        if (vhost && vhost->ssl_ctx) {
            SSL_set_SSL_CTX(ssl, vhost->ssl_ctx);
        }
    }

    return SSL_TLSEXT_ERR_OK;
}
```

note: I made a fix for the context leak.
